services:
  web:
    build: web
    volumes:
      - ./web:/app/web
    ports:
      - "3000:3000"
    working_dir: /app/web
    command: ["npm", "run", "dev", "--"]
  server:
    build: server
    volumes:
      - ./server:/app/server
    ports:
      - "5000:5000"
    working_dir: /app/server
    command: ["npm", "run", "dev", "--"]
