services:
  web:
    image: node:18-slim
    volumes:
      - ./web:/app/web
    ports:
      - "3000:3000"
    working_dir: /app/web
    command: sh -c "npm install && npm run dev"

  server:
    image: node:18-slim
    volumes:
      - ./server:/app/server
    ports:
      - "5000:5000"
    working_dir: /app/server
    command: sh -c "npm install && npm run dev"
